import Head from "next/head";
import TowerCard from "../components/tower-card";
import { useGetUserTowers, useGetUser } from "../hooks/useApiRequest";
import { Box, Typography } from "@mui/material";

import Layout from "../components/layout";

export default function Home() {
  const { towers } = useGetUserTowers();
  const { user } = useGetUser();

  // if (error) return <h1>Something went wrong!</h1>;
  if (!towers || !user) return <h1>Loading...</h1>;

  return (
    <div>
      <Head>
        <title>Next SWR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Box sx={{ my: 6 }}>
            <Typography variant="h4" component="h1" gutterBottom>
              Welcome back
            </Typography>

            <Typography
              color="text.secondary"
              variant="h6"
              component="div"
              gutterBottom
            >
              {user.name}
            </Typography>
          </Box>
          <Box sx={{ my: 4 }}>
            <Typography variant="h4" component="h1" gutterBottom>
              Your current towers
            </Typography>
            {towers.map((tower) => (
              <TowerCard tower={tower} key={tower._id} />
            ))}
          </Box>
        </Layout>
      </main>
    </div>
  );
}
