import Head from "next/head";
import TowerCard from "../components/tower-card";
import { useGetUserTowers, useGetUser } from "../hooks/useApiRequest";
import { Box, Container, Typography } from "@mui/material";
import Image from "next/image";
import Layout from "../components/layout";

export default function Home() {
  const { data: towers } = useGetUserTowers();
  const { user } = useGetUser();

  // if (error) return <h1>Something went wrong!</h1>;
  if (!towers || !user) return <h1>Loading...</h1>;

  return (
    <div>
      <Head>
        <title>Next SWR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Box sx={{ my: 6 }}>
            <Typography variant="h4" component="h1" gutterBottom>
              Welcome back
            </Typography>

            <Typography
              color="text.secondary"
              variant="h6"
              component="div"
              gutterBottom
            >
              {user.name}
            </Typography>
          </Box>
          <Box sx={{ my: 4 }}>
            <Typography variant="h4" component="h1" gutterBottom>
              Your current towers
            </Typography>
            {towers.map((tower) => (
              <TowerCard tower={tower} key={tower._id} />
            ))}
          </Box>
        </Layout>
      </main>
    </div>
  );
}

//<Image src="/gradient-background.jpg" alt="header" width="1750" height="200"/>
//<Container maxWidth="sm" sx={{py: 10}}>
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
//
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//
//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>
//
//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>
//
//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>
//
//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>
//
//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>
//
//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//
//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
